'use strict';
const fs=require('node:fs'),path=require('node:path'),{DatabaseSync}=require('node:sqlite'),crypto=require('node:crypto');
const {edit}=require('./database-edit.cjs'),{cutoff}=require('./old-chats.cjs');
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function json(v){return JSON.parse(Buffer.isBuffer(v)||v instanceof Uint8Array?Buffer.from(v).toString():v);}
function decodeSummary(s){try{s=typeof s==='string'?JSON.parse(s):s;return s&&typeof s.summary==='string'&&s.summary.length&&typeof s.truncationLastBubbleIdInclusive==='string'?s:null;}catch{return null;}}
function supported(c){return Number.isInteger(c._v)&&c._v>=2&&c._v<=18&&!c.createdFromBackgroundAgent&&!c.agentBackend&&Array.isArray(c.fullConversationHeadersOnly)&&(!c.conversationState||typeof c.conversationState==='string'&&c.conversationState.startsWith('~'));}
function kind(c){return c.subagentInfo||c.isSpecSubagent||c.isBestOfNSubcomposer?'subagent':'main';}
function list(db){if(!db.prepare("SELECT 1 FROM sqlite_master WHERE name='cursorDiskKV'").get())return [];const all=[];for(const row of db.prepare("SELECT key,value FROM cursorDiskKV WHERE key GLOB 'composerData:*' AND value IS NOT NULL").iterate()){try{const c=json(row.value);if(uuid.test(c.composerId)&&row.key==='composerData:'+c.composerId)all.push({c,raw:row.value});}catch{}}return all;}
function planOne(db,c,raw){
 if(!supported(c))return null;const headers=c.fullConversationHeadersOnly;if(!headers.length||headers.some(x=>!uuid.test(x.bubbleId))||new Set(headers.map(x=>x.bubbleId)).size!==headers.length)return null;
 const rows=new Map();for(const r of db.prepare("SELECT key,value FROM cursorDiskKV WHERE key GLOB ? AND value LIKE '%conversationSummary%'").iterate('bubbleId:'+c.composerId+':*')){try{rows.set(r.key.split(':')[2],{value:json(r.value),raw:r.value});}catch{return null;}}
 let summaryIndex=-1,boundary=-1;
 for(let i=headers.length-1;i>=0;i--){const s=decodeSummary(rows.get(headers[i].bubbleId)?.value.conversationSummary);if(!s)continue;const j=headers.findIndex(h=>h.bubbleId===s.truncationLastBubbleIdInclusive||h.serverBubbleId===s.truncationLastBubbleIdInclusive);if(j>=0&&j<i){summaryIndex=i;boundary=j;break;}}
 if(boundary<1)return null;
 for(const h of headers){if(rows.has(h.bubbleId))continue;const r=db.prepare('SELECT value FROM cursorDiskKV WHERE key=?').get('bubbleId:'+c.composerId+':'+h.bubbleId);if(!r?.value)return null;try{rows.set(h.bubbleId,{value:json(r.value),raw:r.value});}catch{return null;}}
 // Keep the truncation anchor and first human: Cursor's loader uses them to recover and group turns.
 const keep=new Set(headers.slice(boundary).map(x=>x.bubbleId));const first=headers.find(x=>x.type===1);if(first)keep.add(first.bubbleId);
 // Referenced bubbles remain, including anchors required by retained summaries.
 const rootReferences=JSON.stringify({latestConversationSummary:c.latestConversationSummary,context:c.context,capabilityContexts:c.capabilityContexts,firstTodoWriteBubble:c.firstTodoWriteBubble,generatingBubbleIds:c.generatingBubbleIds});
 let changed=true;while(changed){changed=false;const text=rootReferences+JSON.stringify([...keep].map(id=>rows.get(id).value));for(const h of headers.slice(0,boundary))if(!keep.has(h.bubbleId)&&(text.includes(h.bubbleId)||(h.serverBubbleId&&text.includes(h.serverBubbleId)))){keep.add(h.bubbleId);changed=true;}}
 const remove=headers.filter(h=>!keep.has(h.bubbleId)).map(h=>h.bubbleId);if(!remove.length)return null;
 // Modern agent state and content-addressed blobs remain byte-for-byte intact. This operation
 // prunes stored message history, never the agent's serialized current context or shared blobs.
 const next={...c,fullConversationHeadersOnly:headers.filter(h=>keep.has(h.bubbleId)),conversationMap:Object.fromEntries(Object.entries(c.conversationMap||{}).filter(([id])=>keep.has(id)))};
 for(const k of ['currentBubbleId','editingBubbleId','selectedBubbleId'])if(remove.includes(next[k]))delete next[k];
 const messagesHash=hash(headers.map(h=>hash(rows.get(h.bubbleId).raw)).join(''));
 const saving=remove.reduce((n,id)=>n+Buffer.byteLength(rows.get(id).raw),0)+Buffer.byteLength(raw)-Buffer.byteLength(JSON.stringify(next));
 return {id:c.composerId,title:c.name||c.composerId,kind:kind(c),saving,bytes:saving,remove,next,sourceHash:hash(raw),messagesHash,summaryBubbleId:headers[summaryIndex].bubbleId,boundaryBubbleId:headers[boundary].bubbleId,lastActivity:Math.max(c.lastUpdatedAt||0,c.createdAt||0)};
}
function scan(file,{action='compact',months=3,selection='main',now=new Date(),transcriptFiles=[]}={}){const db=new DatabaseSync(file,{readOnly:true});try{const all=list(db),protectedIds=new Set();for(const {c}of all){for(const k of ['subComposerIds','subagentComposerIds'])for(const id of c[k]||[])if(action==='delete')protectedIds.add(id);for(const id of [c.subagentInfo?.parentComposerId,c.parentComposerId])if(id)protectedIds.add(id);if((c.subComposerIds||[]).length||(c.subagentComposerIds||[]).length)protectedIds.add(c.composerId);}
 const out=[];for(const {c,raw}of all){if(protectedIds.has(c.composerId))continue;if(action==='compact'){if(kind(c)!==selection)continue;const p=planOne(db,c,raw);if(p)out.push({...p,file});}else{const exportFiles=transcriptFiles.filter(file=>path.basename(file).replace(/\.(txt|jsonl)$/,'')===c.composerId&&/\.(txt|jsonl)$/.test(file)&&fs.existsSync(file));if(exportFiles.some(file=>fs.lstatSync(file).isSymbolicLink()))continue;const activity=Math.max(c.lastUpdatedAt||0,c.createdAt||0,...exportFiles.map(file=>fs.statSync(file).mtimeMs));if(!Number.isFinite(activity)||!activity||activity>=cutoff(months,now)||c.createdFromBackgroundAgent||c.gitWorktree||c.reservedWorktree||c.isCreatingWorktree)continue;const bytes=db.prepare("SELECT coalesce(sum(length(value)),0) n FROM cursorDiskKV WHERE key=? OR key GLOB ?").get('composerData:'+c.composerId,'*:'+c.composerId+':*').n;out.push({file,id:c.composerId,title:c.name||c.composerId,lastActivity:activity,kind:kind(c),sourceHash:hash(raw),exportFiles:exportFiles.map(file=>({file,hash:hash(fs.readFileSync(file)),bytes:fs.statSync(file).size})),bytes:bytes+exportFiles.reduce((n,file)=>n+fs.statSync(file).size,0),saving:bytes});}}return out;
 }finally{db.close();}}
function filterIndex(value,ids){const parsed=json(value);if(Array.isArray(parsed))return JSON.stringify(parsed.filter(x=>!ids.has(typeof x==='string'?x:x?.composerId)));if(!parsed||typeof parsed!=='object')throw Error('Unrecognized Cursor index');let next={...parsed};for(const k of ['allComposers','selectedComposerIds','lastFocusedComposerIds'])if(Array.isArray(next[k]))next[k]=next[k].filter(x=>!ids.has(typeof x==='string'?x:x?.composerId));return JSON.stringify(next);}
async function apply(items,action,root,vault,guard,transcriptRoot){if(!['compact','delete'].includes(action))throw Error('Unknown Cursor action');const groups=new Map();for(const p of items){if(!groups.has(p.file))groups.set(p.file,[]);groups.get(p.file).push(p);}let saved=0;
 for(const [file,plans]of groups){const r=await edit(file,root,vault,guard,db=>{for(const p of plans){const row=db.prepare('SELECT value FROM cursorDiskKV WHERE key=?').get('composerData:'+p.id);if(!row?.value||hash(row.value)!==p.sourceHash)throw Error('Cursor chat changed');if(action==='compact'){const fresh=planOne(db,json(row.value),row.value);if(!fresh||fresh.messagesHash!==p.messagesHash||JSON.stringify(fresh.remove)!==JSON.stringify(p.remove))throw Error('Cursor checkpoint changed');db.prepare('UPDATE cursorDiskKV SET value=? WHERE key=?').run(JSON.stringify(fresh.next),'composerData:'+p.id);for(const id of fresh.remove)db.prepare('DELETE FROM cursorDiskKV WHERE key=?').run('bubbleId:'+p.id+':'+id);for(const h of fresh.next.fullConversationHeadersOnly)if(!db.prepare('SELECT 1 FROM cursorDiskKV WHERE key=? AND value IS NOT NULL').get('bubbleId:'+p.id+':'+h.bubbleId))throw Error('Dangling Cursor message');}
 else{db.prepare('DELETE FROM cursorDiskKV WHERE key=?').run('composerData:'+p.id);for(const prefix of ['bubbleId','checkpointId','codeBlockDiff','codeBlockPartialInlineDiffFates','ofsContent','messageRequestContext','composerVirtualRowHeights'])db.prepare('DELETE FROM cursorDiskKV WHERE key GLOB ?').run(prefix+':'+p.id+':*');if(db.prepare("SELECT 1 FROM sqlite_master WHERE name='composerHeaders'").get())db.prepare('DELETE FROM composerHeaders WHERE composerId=?').run(p.id);}}
 if(action==='delete'){const ids=new Set(plans.map(p=>p.id));for(const key of ['composer.composerData','composer.composerHeaders']){const r=db.prepare('SELECT value FROM ItemTable WHERE key=?').get(key);if(r?.value)db.prepare('UPDATE ItemTable SET value=? WHERE key=?').run(filterIndex(r.value,ids),key);}}
 });saved+=r.saved;}
 if(action==='delete'){
  const ids=new Set(items.map(p=>p.id)),files=(await require('./chat-storage.cjs').filesIn(root)).filter(p=>path.basename(p)==='state.vscdb'&&!groups.has(p));
  for(const file of files){const db=new DatabaseSync(file,{readOnly:true});let needed=false;try{for(const key of ['composer.composerData','composer.composerHeaders']){const row=db.prepare('SELECT value FROM ItemTable WHERE key=?').get(key);if(row?.value&&[...ids].some(id=>String(row.value).includes(id)))needed=true;}}finally{db.close();}
   if(needed){const r=await edit(file,root,vault,guard,db=>{for(const key of ['composer.composerData','composer.composerHeaders']){const row=db.prepare('SELECT value FROM ItemTable WHERE key=?').get(key);if(row?.value)db.prepare('UPDATE ItemTable SET value=? WHERE key=?').run(filterIndex(row.value,ids),key);}});saved+=r.saved;}
  }
 }
 if(action==='delete')for(const p of items)for(const e of p.exportFiles||[]){await guard();if(!transcriptRoot)throw Error('Missing transcript storage root');const actual=fs.realpathSync(e.file),allowed=fs.realpathSync(transcriptRoot);if(!require('./clean-subagents.cjs').inside(allowed,actual)||hash(fs.readFileSync(actual))!==e.hash)throw Error('Cursor transcript changed or moved');await vault.capture(actual);await guard();if(hash(fs.readFileSync(actual))!==e.hash)throw Error('Cursor transcript changed before deletion');fs.unlinkSync(actual);await vault.commit(actual,null);saved+=e.bytes;}
 return saved;
}
module.exports={scan,apply,planOne,list,json,filterIndex,decodeSummary};
