'use strict';
const fs=require('node:fs'),f=fs.promises,path=require('node:path'),crypto=require('node:crypto'),w=require('./protobuf-wire.cjs'),core=require('./clean-subagents.cjs'),{cutoff}=require('./old-chats.cjs');
const {edit}=require('./database-edit.cjs');
// Format key embedded in Antigravity 1.21.9's trajectory saver, not an account credential.
const KEY=Buffer.from('c2FmZUNvZGVpdW13b3JsZEtlWXNlY3JldEJhbGxvb24=','base64');
function decrypt(buffer){if(buffer.length<28)throw Error('Truncated Antigravity envelope');const d=crypto.createDecipheriv('aes-256-gcm',KEY,buffer.subarray(0,12));d.setAuthTag(buffer.subarray(-16));return Buffer.concat([d.update(buffer.subarray(12,-16)),d.final()]);}
function encrypt(plain){const nonce=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',KEY,nonce);return Buffer.concat([nonce,c.update(plain),c.final(),c.getAuthTag()]);}
function timestamp(rows,n){const field=w.get(rows,n);if(!field?.data)return 0;const t=w.fields(field.data);return w.num(t,1)*1000+w.num(t,2)/1e6;}
function inspect(buffer){const plain=decrypt(buffer),rows=w.fields(plain),id=w.str(rows,6),trajectoryId=w.str(rows,1);if(!/^[0-9a-f-]{36}$/i.test(id)||!trajectoryId||rows.some(x=>![1,2,3,4,5,6,7,8,9].includes(x.number)))throw Error('Unrecognized Antigravity trajectory');
 const steps=rows.filter(x=>x.number===2).map(x=>({raw:x,data:w.fields(x.data)}));const meta=w.get(rows,7),metadata=meta?w.fields(meta.data):[];let lastActivity=timestamp(metadata,2);for(const step of steps){const field=w.get(step.data,5);if(field){const m=w.fields(field.data);for(const n of [1,6,7,8,22])lastActivity=Math.max(lastActivity,timestamp(m,n));}}
 const parent=[w.str(metadata,5),w.str(metadata,6)].find(x=>x&&x!==id)||'',references=rows.filter(x=>x.number===5).map(x=>w.str(w.fields(x.data),1));
 let latest=-1;const covered=new Set(),checkpoints=[];
 let title='';for(let i=0;i<steps.length;i++){const field=w.get(steps[i].data,30);if(!field)continue;const cp=w.fields(field.data);checkpoints.push(i);title=w.str(cp,10)||title;if(w.num(steps[i].data,4)!==3||w.num(cp,9)||w.num(cp,16)||w.num(cp,17)||!w.str(cp,5))continue;const explicit=cp.filter(x=>x.number===3);if(explicit.length){const indices=[];for(const field of explicit){if(field.wire===0)indices.push(Number(field.value));else if(field.wire===2){let offset=0;while(offset<field.data.length){const v=w.varint(field.data,offset);indices.push(Number(v.value));offset=v.offset;}}else throw Error('Invalid checkpoint indices');}if(indices.some(x=>!Number.isInteger(x)||x<0||x>=i))continue;for(const j of indices)covered.add(j);}else{const start=w.num(cp,11),end=w.num(cp,12);if(!Number.isInteger(start)||!Number.isInteger(end)||start<0||end>i||end<=start)continue;for(let j=start;j<end;j++)covered.add(j);}latest=i;}
 // Fixed ordinal placeholders preserve every trajectory/step reference. Summaries are incremental,
 // so all checkpoint records survive; deleting earlier summaries would discard current knowledge.
 const remove=[];if(latest>=0)for(let i=1;i<latest;i++)if(covered.has(i)&&!checkpoints.includes(i)&&w.num(steps[i].data,1)!==1)remove.push(i);
 const removed=new Set(remove);let stepIndex=0;const reduced=Buffer.concat(rows.map(row=>{if(row.number!==2)return row.raw;const i=stepIndex++;if(!removed.has(i))return row.raw;const metadata=w.get(steps[i].data,5),status=w.get(steps[i].data,4);return w.bytes(2,Buffer.concat([w.uint(1,1),...(status?[status.raw]:[]),...(metadata?[metadata.raw]:[]),w.bytes(7,Buffer.alloc(0))]));}));
 return {plain,rows,steps,id,trajectoryId,parent,references,title:title||id,kind:parent?'subagent':'main',lastActivity,latest,checkpoints,remove,reduced,saving:plain.length-reduced.length};
}
async function scan(root,{action='compact',months=3,selection='main',now=new Date()}={}){const dir=path.join(root,'conversations');if(!fs.existsSync(dir))return [];const items=[];
 const skipped=[];for(const entry of await f.readdir(dir,{withFileTypes:true})){if(!entry.isFile()||!entry.name.endsWith('.pb'))continue;const file=path.join(dir,entry.name);try{const b=await f.readFile(file),p=inspect(b),s=await f.stat(file);if(entry.name!==p.id+'.pb')throw Error('Trajectory ID does not match filename');items.push({...p,file,bytes:s.size,mtimeMs:s.mtimeMs,sourceHash:crypto.createHash('sha256').update(b).digest('hex'),lastActivity:Math.max(p.lastActivity,s.mtimeMs)});}catch(e){skipped.push({file,reason:e.message});}}
 const parents=new Set(items.map(p=>p.parent).filter(Boolean)),references=new Set(items.flatMap(p=>p.references));const result=items.filter(p=>!parents.has(p.id)&&!references.has(p.trajectoryId)&&(action==='compact'?p.kind===selection&&p.saving>0:p.lastActivity>0&&p.lastActivity<cutoff(months,now))).map(({plain,rows,steps,reduced,...p})=>p);
 // An unreadable payload may contain a dependency on an otherwise eligible chat.
 if(skipped.length)result.length=0;result.skipped=skipped;return result;
}
async function compact(items,root,vault,guard){let saved=0;for(const plan of items){await guard();const actual=await f.realpath(plan.file);if(!core.inside(await f.realpath(root),actual))throw Error('Trajectory outside storage');if(await core.digest(actual)!==plan.sourceHash)throw Error('Antigravity chat changed');const original=await f.stat(actual),current=inspect(await f.readFile(actual));if(current.saving!==plan.saving)throw Error('Antigravity checkpoint changed');await vault.capture(actual);const temp=actual+'.cleaner-'+crypto.randomUUID()+'.tmp';try{const reduced=encrypt(current.reduced);if(!decrypt(reduced).equals(current.reduced))throw Error('Antigravity encryption round trip failed');await f.writeFile(temp,reduced,{flag:'wx',mode:original.mode});await f.utimes(temp,original.atime,original.mtime);await guard();if(await core.digest(actual)!==plan.sourceHash)throw Error('Antigravity chat changed before replacement');await f.rename(temp,actual);await vault.commit(actual,await core.digest(actual));saved+=current.saving;}finally{await f.unlink(temp).catch(()=>{});}}return saved;}
function filterSummaries(value,ids){const buffer=Buffer.from(String(value),'base64'),rows=w.fields(buffer);return Buffer.concat(rows.filter(row=>{if(row.number!==1)return true;if(row.wire!==2)throw Error('Unrecognized Antigravity index');const entry=w.fields(row.data);return !ids.has(w.str(entry,1));}).map(x=>x.raw)).toString('base64');}
function filterSessionIndex(value,ids){const parsed=JSON.parse(String(value));if(parsed.version!==1||!parsed.entries||Array.isArray(parsed.entries)||typeof parsed.entries!=='object')throw Error('Unrecognized Antigravity session index');return JSON.stringify({...parsed,entries:Object.fromEntries(Object.entries(parsed.entries).filter(([key])=>!ids.has(key)))});}
async function deleteChats(items,root,userRoot,databases,vault,guard){const ids=new Set(items.map(p=>p.id));await guard();for(const p of items){if(await core.digest(p.file)!==p.sourceHash)throw Error('Antigravity chat changed');await vault.capture(p.file);}
 // Update the UI catalogue before removing its payloads. Workspace/project files are never deleted.
 const changes=[];for(const file of databases){const {DatabaseSync}=require('node:sqlite'),db=new DatabaseSync(file,{readOnly:true});try{const patches=[];for(const [key,filter]of [['antigravityUnifiedStateSync.trajectorySummaries',filterSummaries],['chat.ChatSessionStore.index',filterSessionIndex]]){const row=db.prepare('SELECT value FROM ItemTable WHERE key=?').get(key);if(!row?.value)continue;const value=filter(row.value,ids);if(value!==row.value)patches.push({key,before:row.value,value});}if(patches.length)changes.push({file,patches});}finally{db.close();}}
 for(const {file,patches}of changes)await edit(file,userRoot,vault,guard,db=>{for(const patch of patches){if(db.prepare('SELECT value FROM ItemTable WHERE key=?').get(patch.key)?.value!==patch.before)throw Error('Antigravity index changed');db.prepare('UPDATE ItemTable SET value=? WHERE key=?').run(patch.value,patch.key);}});
 let saved=0;for(const p of items){await guard();const actual=await f.realpath(p.file);if(!core.inside(await f.realpath(root),actual)||await core.digest(actual)!==p.sourceHash)throw Error('Trajectory changed before deletion');await f.unlink(actual);await vault.commit(actual,null);saved+=p.bytes;}return saved;
}
module.exports={decrypt,encrypt,inspect,scan,compact,deleteChats,filterSummaries,filterSessionIndex};

